# Generated by Django 4.0.4 on 2022-05-16 15:29

import cnab_reader.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnab_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnabmodel',
            name='cartao',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cnabmodel',
            name='nome_dono_loja',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cnabmodel',
            name='nome_loja',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='cnabmodel',
            name='tipo_transacao',
            field=models.IntegerField(validators=[cnab_reader.models_validators.validate_transaction]),
        ),
        migrations.AlterField(
            model_name='cnabmodel',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
